In [1]:
# 데이터 준비
import pandas as pd
path = "https://raw.githubusercontent.com/blackdew/ml-tensorflow/master/data/csv/iris.csv"
df = pd.read_csv(path)

print(df.columns)
df.head(2)

Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종'], dtype='object')


꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭      품종
0   5.1  3.5    1.4   0.2  setosa
1   4.9  3.0    1.4   0.2  setosa

In [3]:
# one-hot encoding
df = pd.get_dummies(df)
print(df.columns)
df.head(2)

Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종_setosa', '품종_versicolor',
       '품종_virginica'],
      dtype='object')


꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_setosa  품종_versicolor  품종_virginica
0   5.1  3.5    1.4   0.2          1              0             0
1   4.9  3.0    1.4   0.2          1              0             0

In [5]:
x_train = df[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
y_train = df[['품종_setosa', '품종_versicolor', '품종_virginica']]
print(x_train.shape, y_train.shape)

(150, 4) (150, 3)


In [6]:
import tensorflow as tf
# 모델 구성
X = tf.keras.Input(shape=[4])
Y = tf.keras.layers.Dense(3, activation='softmax')(X)

model = tf.keras.Model(X,Y)
model.compile(loss='categorical_crossentropy', metrics='accuracy')
# activation function이 sigmoid 일 때는 binary_crossentopy

In [8]:
# 모델 학습 - 1000번 학습
model.fit(x_train, y_train, epochs=1000, verbose=0)
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
5/5 [==============================] - 0s 1ms/step - loss: 0.1479 - accuracy: 0.9867
Epoch 2/5
5/5 [==============================] - 0s 1ms/step - loss: 0.1468 - accuracy: 0.9867
Epoch 3/5
5/5 [==============================] - 0s 1ms/step - loss: 0.1467 - accuracy: 0.9867
Epoch 4/5
5/5 [==============================] - 0s 1ms/step - loss: 0.1473 - accuracy: 0.9867
Epoch 5/5
5/5 [==============================] - 0s 2ms/step - loss: 0.1468 - accuracy: 0.9867


In [14]:
# 모델 이용 및 결과 확인
print(model.predict(x_train[-5:])) # 맨 뒤 5개
print(y_train[-5:])

1/1 [==============================] - 0s 21ms/step
[[6.3170847e-07 1.6049318e-01 8.3950621e-01]
 [1.2977540e-06 2.1955638e-01 7.8044236e-01]
 [1.9521685e-06 2.4399385e-01 7.5600415e-01]
 [2.7511268e-07 8.3965153e-02 9.1603458e-01]
 [2.8404638e-06 2.2173668e-01 7.7826047e-01]]
     품종_setosa  품종_versicolor  품종_virginica
145          0              0             1
146          0              0             1
147          0              0             1
148          0              0             1
149          0              0             1
