## chapter11 LAB

<h5>numPy</h5>
- 파이썬의 과학 계산을 위한 가장 기본적인 패키지 <br>
- 다차원 배열과 행렬 객체가 포함

In [2]:
import numpy as np
# array는 같은 타입
# array class의 constructor
a = np.array([1,2,3])   # 넘파이 ndarray 객체 생성

print(a.shape) # a 객체의 형태
print(a.ndim) # 차원
print(a.dtype) # 내부 자료형
print(a.itemsize) # 객체 내부 자료형이 차지하는 메모리 크기
print(a.size)  # a객체의 전체 크기


(3,)
1
int32
4
3


In [8]:
b = np.array([4,5,6], dtype='int64')    # default는 int32? 시험
c = a+b
c = a.__add__(b) # 시험
print(c.dtype)   # 큰 것으로 conversion

# d = np.array(1,2,3,4)
#  : TypeErrorarray() takes from 1 to 2 positional arguments but 4 were given

# a = np.array([1,'two', 3, 4], dtype = np.int32) -> 오류 incalid literal for int()
a = np.array([1,'two', 3, 4])
print(a)
# 스트링으로 자동 형 변환

int64
['1' 'two' '3' '4']


### LAB 11-1

In [4]:
# (1)
a = np.array([0,1,2,3,4,5,6,7,8,9])
print(f'array({list(a)})')
# (2)
b = np.array(list(range(10)))
print(f'array({list(b)})')
# (3) 짝수만
c = np.array([x for x in range(10) if x%2==0], dtype=np.int64)
print(f'array({list(c)})')
# (4)
print(f'c.shape = {c.shape}')
print(f'c.ndim = {c.ndim}')
print(f'c.dtype = {c.dtype}')
print(f'c.size = {c.size}')
print(f'c.itemsize = {c.itemsize}')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
array([0, 2, 4, 6, 8])
c.shape = (5,)
c.ndim = 1
c.dtype = int64
c.size = 5
c.itemsize = 8


In [18]:
# 메소드를 외워서 하기보다는 메소드를 알려주면 활용할 수 있도록
a = np.array([1,2,3])
print(a.max())
print(a.min())
print(a.mean())

# flatten()
a = np.array([[1,1],[2,2],[3,3]])
a.flatten()

3
1
2.0


array([1, 1, 2, 2, 3, 3])

In [21]:
a = np.array([1,2,3])
b = np.array([[4,5,6], [7,8,9]])
print(np.append(a,b))

# [a]를 통해 2차원 배열로 만들기
np.append([a],b,axis = 0)
# (3,3) shape의 난수 생성
np.random.rand(3,3)
# 0에서 10사이의 10개의 난수 생성
np.random.randint(0,10,size=10)

[1 2 3 4 5 6 7 8 9]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### LAB 11-2

In [34]:
# (1)
a = np.array([23,45,67,7,2,30,34,82], dtype=np.int64)
print(f'array({a})')
print(f'최댓값 : {a.max()}')
print(f'최솟값 : {a.min()}')
print(f'평균 : {a.mean()}')
print()
# (2)
b = np.random.randint(0,99,size=10)
print(f'array({b})')
print(f'최댓값 : {b.max()}')
print(f'최솟값 : {b.min()}')
print(f'평균 : {b.mean()}')
print()
# (3)
c = np.append(a,b)
print(f'array({c})')


array([23 45 67  7  2 30 34 82])
최댓값 : 82
최솟값 : 2
평균 : 36.25

array([41 42 21 21 47 45 20 35 84 61])
최댓값 : 84
최솟값 : 20
평균 : 41.7

array([23 45 67  7  2 30 34 82 41 42 21 21 47 45 20 35 84 61])


### LAB 11-3

In [39]:
# (1)
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[2,2,2],[2,2,2],[2,2,2]])
# (2)
print(a+b, end='\n\n') 
print(a-b, end='\n\n')
print(a*b, end='\n\n')
print(a/b, end='\n\n')
print(a@b, end='\n\n')
print(a**b, end='\n\n')


[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

[[-1  0  1]
 [ 2  3  4]
 [ 5  6  7]]

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]

[[0.5 1.  1.5]
 [2.  2.5 3. ]
 [3.5 4.  4.5]]

[[12 12 12]
 [30 30 30]
 [48 48 48]]

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]



In [4]:
# ndarray 생성
# 초깃값을 가지는 행렬 생성
np.zeros((2,3)) # 모든 값이 0인 2x3 크기 행렬
np.ones((2,3))  # 모든 값이 1인 2x3 크기 행렬
np.full((2,3), 100) # 모든 값이 100인 2,3크기 행렬
np.eye(3)   # 3x3 크기의 단위행렬
np.random.random((2,3)) # 2,3 크기의 랜덤 행렬

# arrange() 함수
np.arange(0,10)
np.arange(0,10,2)
np.arange(0.10,3)
np.arange(0.0,1.0,0.2)  # arange()의 특징 step을 실수로 줄 수 있다.

np.linspace(0,10,5)  # 0과 10 사이의 5개


array([ 0. ,  2.5,  5. ,  7.5, 10. ])

### LAB 11-4

In [13]:
# (1)
a1 = np.full((3,3), 2)
print('a1 = ', a1)
print()
# (2)
a2 = np.arange(1,13,1)
print('a2 =', a2)
print()
# (3)
a3 = np.arange(3,51,3)
print('a3 =',a3)
print()
# (4)
a4 = np.linspace(0,20,5)
print('a4 =',a4)

a1 =  [[2 2 2]
 [2 2 2]
 [2 2 2]]

a2 = [ 1  2  3  4  5  6  7  8  9 10 11 12]

a3 = [ 3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48]

a4 = [ 0.  5. 10. 15. 20.]


In [22]:
# 마지막 시간에 배운 것이 기말에 나올 확률? 높다
np.arange(0,10).reshape(2,5)
t = np.arange(0,24).reshape(4,3,2)  # 높이, 가로, 세로
print(t);print()
print(np.transpose(t))

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]

[[[ 0  6 12 18]
  [ 2  8 14 20]
  [ 4 10 16 22]]

 [[ 1  7 13 19]
  [ 3  9 15 21]
  [ 5 11 17 23]]]


In [20]:
a = np.arange(6).reshape(3,2)
print(a)
print()
print(np.transpose(a))  # 행렬 바꾸기

[[0 1]
 [2 3]
 [4 5]]
[[0 2 4]
 [1 3 5]]


### LAB 11-5

In [29]:
# (1)
a1 = np.arange(1,13).reshape(2,6)
print(repr(a1))
print()
# (2)
a2 = np.arange(1,31).reshape(3,10)
print(repr(a2))
print()
# (3)
a3 = a2.reshape(6,5)
print(repr(a3))
print()
# (4)
a4 = np.transpose(a3)
print(repr(a4))
print()

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

array([[ 1,  6, 11, 16, 21, 26],
       [ 2,  7, 12, 17, 22, 27],
       [ 3,  8, 13, 18, 23, 28],
       [ 4,  9, 14, 19, 24, 29],
       [ 5, 10, 15, 20, 25, 30]])



In [34]:
# 시험 axis sum,max,mean
a = np.arange(0,6).reshape(3,2)
print(repr(a))
print(repr(a.sum()))
print(repr(a.sum(axis=0)))
print(repr(a.sum(axis=1)))

array([[0, 1],
       [2, 3],
       [4, 5]])
15
array([6, 9])
array([1, 5, 9])


### LAB 11-6
- string, list indexing 시험

In [46]:
# (1)
a = np.random.randint(1,101,15).reshape(3,5)
print(repr(a))
print()
# (2)
print(a.max(axis=0))
print(a.min(axis=0))
print(a.mean(axis=0))
print()
# (3)
print(a.max(axis=1))
print(a.min(axis=1))
print(a.mean(axis=1))


array([[ 88,  73, 100,  24,  43],
       [ 84,   7,  67,  83,  47],
       [ 81,   3,  61,  18,  52]])

[ 88  73 100  83  52]
[81  3 61 18 43]
[84.33333333 27.66666667 76.         41.66666667 47.33333333]

[100  84  81]
[24  7  3]
[65.6 57.6 43. ]


### LAB 11-7

In [7]:
# 넘파이 인덱싱 슬라이싱 시험
# (1)
a = np.arange(1,11)
print('a =',a)
b = a[1:8:2]
print('b =',b)
print()

# (2)
b = a[5:]
print('b =',b)
c = a[6:]
print('c =',c)
d = a[:3]
print('d =',d)
e = a[::2]
print('e =',e)
f = a[::-2]
print('f =',f)

a = [ 1  2  3  4  5  6  7  8  9 10]
b = [2 4 6 8]

b = [ 6  7  8  9 10]
c = [ 7  8  9 10]
d = [1 2 3]
e = [1 3 5 7 9]
f = [10  8  6  4  2]


In [21]:
# 2차원 인덱싱
a = np.arange(0,6).reshape(3,2)
print(a)
print(a[0,1])
print()

# 3차원 인덱싱
b = np.arange(0,24).reshape(4,3,2)
print(b)
# 17 뽑아내기
print(b[2,2,1])

# concatenate()
print(np.concatenate((b[0,0], b[0,2]), axis=0))

[[0 1]
 [2 3]
 [4 5]]
1

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]
17
[0 1 4 5]


### LAB 11-8

In [22]:
a = np.arange(0,24).reshape(4,3,2)

# (1)
print('index\t\telement')
for i in range(0,4):
    for j in range(0,3):
        for k in range(0,2):
            print(f'({i}, {j}, {k})\t{a[i,j,k]}')

index		element
(0, 0, 0)	0
(0, 0, 1)	1
(0, 1, 0)	2
(0, 1, 1)	3
(0, 2, 0)	4
(0, 2, 1)	5
(1, 0, 0)	6
(1, 0, 1)	7
(1, 1, 0)	8
(1, 1, 1)	9
(1, 2, 0)	10
(1, 2, 1)	11
(2, 0, 0)	12
(2, 0, 1)	13
(2, 1, 0)	14
(2, 1, 1)	15
(2, 2, 0)	16
(2, 2, 1)	17
(3, 0, 0)	18
(3, 0, 1)	19
(3, 1, 0)	20
(3, 1, 1)	21
(3, 2, 0)	22
(3, 2, 1)	23


In [29]:
# (2)
print(repr(np.concatenate((a[0,0], a[1,0]), axis=0)))
print(repr(np.concatenate((a[0,0], a[2,1]), axis=0)))
print(repr(np.concatenate((a[0], a[1]), axis=0)))
print(repr(np.concatenate((a[0], a[1]), axis=1)))

array([0, 1, 6, 7])
array([ 0,  1, 14, 15])
array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])
array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])


In [32]:
# 2차원 배열의 슬라이싱
a = np.arange(0,9).reshape(3,3)
print(a[:,0])

[0 3 6]


### LAB 11-9

In [52]:
# (1)
a = np.arange(0,16).reshape(4,4)
b = a[:,1]
print('b =',b)
c = a[2,1:]
print('c =',c)
d = a[:2,:2]
print('d =',d)
e = a[1:3,1:3]
print('e =',e)


b = [ 1  5  9 13]
c = [ 9 10 11]
d = [[0 1]
 [4 5]]
e = [[ 5  6]
 [ 9 10]]


In [50]:
# (2)
f = np.concatenate((a[0,:4], a[1,:3]), axis=0)
print('f =',f)
g = np.concatenate((a[2:]))
print('g =', g)
h = np.concatenate((a[1,1:], a[3,1:]), axis=0)
print('h =', h)

f = [0 1 2 3 4 5 6]
g = [ 8  9 10 11 12 13 14 15]
h = [ 5  6  7 13 14 15]


In [58]:
# 선형 방적식 풀이, 행렬식
import numpy as np
a = np.array([[2,3], [1,-2]])
b = np.array([1,4])
x = np.linalg.solve(a,b)
print(x)

# 3차원 배열의 인덱스와 concatenate()
a = np.array([[1,2],[3,4]])
np.linalg.det(a)    # 행렬식

[ 2. -1.]


-2.0000000000000004

### LAB 11-10

In [60]:
# (1)
a = np.array([[1,1,-1],[2,-1,3],[1,2,1]])
b = np.array([0,9,8])
x = np.linalg.solve(a,b)
print(f'x = {x[0]}, y = {x[1]}, z = {x[2]}')

# (2)
a = np.array([[1,1,-1],[2,-1,3],[1,2,1]], dtype = 'int32')
print('det(A) =',np.linalg.det(a).round(1))

x = 1.0, y = 2.0, z = 3.0
det(A) = -11.0


In [64]:
# (3)
a = np.array([[-1,3],[2,1]])
x1 = np.linalg.det(a)
b = np.array([[2,3],[1,1]])
x2 = np.linalg.det(a)
a = np.array([[2,-1],[1,2]])
x3 = np.linalg.det(a)
print(x1-x2+x3)

5.000000000000001
